server:
  port: 15002
spring:
  application:
    name: user-service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:81/
        username: nacos
        password: nacos
  main:
    allow-bean-definition-overriding: true
