server:
  port: 15001
spring:
  application:
    name: order-service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:81/
        username: nacos
        password: nacos
  rabbitmq:
    addresses: localhost:5672
    stream:
      username: guest
      password: guest
  main:
    allow-bean-definition-overriding: true